# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 658)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.Image = QtWidgets.QWidget()
        self.Image.setObjectName("Image")
        self.Image_path = QtWidgets.QPushButton(self.Image)
        self.Image_path.setGeometry(QtCore.QRect(10, 10, 90, 28))
        self.Image_path.setObjectName("Image_path")
        self.Image_path_text = QtWidgets.QLabel(self.Image)
        self.Image_path_text.setGeometry(QtCore.QRect(110, 20, 431, 16))
        self.Image_path_text.setObjectName("Image_path_text")
        self.textEdit = QtWidgets.QTextEdit(self.Image)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(630, 10, 141, 31))
        self.textEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.Image_result = QtWidgets.QLabel(self.Image)
        self.Image_result.setGeometry(QtCore.QRect(580, 20, 41, 16))
        self.Image_result.setObjectName("Image_result")
        self.image_holder = QtWidgets.QLabel(self.Image)
        self.image_holder.setGeometry(QtCore.QRect(10, 60, 761, 450))
        self.image_holder.setStyleSheet("Background-color: #000;")
        self.image_holder.setObjectName("image_holder")
        self.tabWidget.addTab(self.Image, "")
        self.Image1 = QtWidgets.QWidget()
        self.Image1.setObjectName("Image1")
        self.Video_path = QtWidgets.QPushButton(self.Image1)
        self.Video_path.setGeometry(QtCore.QRect(10, 10, 90, 28))
        self.Video_path.setObjectName("Video_path")
        self.video_path_text = QtWidgets.QLabel(self.Image1)
        self.video_path_text.setGeometry(QtCore.QRect(110, 20, 431, 16))
        self.video_path_text.setObjectName("video_path_text")
        self.video_holder = QtWidgets.QLabel(self.Image1)
        self.video_holder.setGeometry(QtCore.QRect(10, 60, 761, 450))
        self.video_holder.setStyleSheet("Background-color: #000;")
        self.video_holder.setObjectName("video_holder")
        self.play_buttom = QtWidgets.QPushButton(self.Image1)
        self.play_buttom.setGeometry(QtCore.QRect(10, 520, 90, 28))
        self.play_buttom.setObjectName("play_buttom")
        self.tabWidget.addTab(self.Image1, "")
        self.Real_time = QtWidgets.QWidget()
        self.Real_time.setObjectName("Real_time")
        self.tabWidget.addTab(self.Real_time, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuModel = QtWidgets.QMenu(self.menuFile)
        self.menuModel.setObjectName("menuModel")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLabel = QtWidgets.QAction(MainWindow)
        self.actionLabel.setObjectName("actionLabel")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionCamera = QtWidgets.QAction(MainWindow)
        self.actionCamera.setObjectName("actionCamera")
        self.actionAbout_Us = QtWidgets.QAction(MainWindow)
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.actionLPRNet = QtWidgets.QAction(MainWindow)
        self.actionLPRNet.setObjectName("actionLPRNet")
        self.actionObject_Detection = QtWidgets.QAction(MainWindow)
        self.actionObject_Detection.setObjectName("actionObject_Detection")
        self.menuModel.addAction(self.actionLPRNet)
        self.menuModel.addAction(self.actionObject_Detection)
        self.menuFile.addAction(self.menuModel.menuAction())
        self.menuFile.addAction(self.actionLabel)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveAs)
        self.menuTool.addAction(self.actionCamera)
        self.menuHelp.addAction(self.actionAbout_Us)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setProperty("text", _translate("MainWindow", "Default"))
        self.Image_path.setText(_translate("MainWindow", "Choose image"))
        self.Image_path_text.setText(_translate("MainWindow", "Path"))
        self.Image_result.setText(_translate("MainWindow", "Result"))
        self.image_holder.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Image), _translate("MainWindow", "Image"))
        self.Video_path.setText(_translate("MainWindow", "Choose video"))
        self.video_path_text.setText(_translate("MainWindow", "Path"))
        self.video_holder.setText(_translate("MainWindow", "TextLabel"))
        self.play_buttom.setText(_translate("MainWindow", "Play"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Image1), _translate("MainWindow", "Video"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Real_time), _translate("MainWindow", "Real time"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuModel.setTitle(_translate("MainWindow", "Models"))
        self.menuTool.setTitle(_translate("MainWindow", "Setting"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLabel.setText(_translate("MainWindow", "Label"))
        self.actionLabel.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As..."))
        self.actionCamera.setText(_translate("MainWindow", "Camera"))
        self.actionAbout_Us.setText(_translate("MainWindow", "About Us"))
        self.actionLPRNet.setText(_translate("MainWindow", "LPRNet"))
        self.actionObject_Detection.setText(_translate("MainWindow", "Object Detection"))

