# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.Image = QtWidgets.QWidget()
        self.Image.setObjectName("Image")
        self.Image_path = QtWidgets.QPushButton(self.Image)
        self.Image_path.setGeometry(QtCore.QRect(10, 10, 90, 28))
        self.Image_path.setObjectName("Image_path")
        self.Image_path_text = QtWidgets.QLabel(self.Image)
        self.Image_path_text.setGeometry(QtCore.QRect(110, 20, 431, 16))
        self.Image_path_text.setObjectName("Image_path_text")
        self.image_holder = QtWidgets.QLabel(self.Image)
        self.image_holder.setGeometry(QtCore.QRect(10, 60, 761, 450))
        self.image_holder.setStyleSheet("Background-color: #000;")
        self.image_holder.setText("")
        self.image_holder.setObjectName("image_holder")
        self.tabWidget.addTab(self.Image, "")
        self.Image1 = QtWidgets.QWidget()
        self.Image1.setObjectName("Image1")
        self.Video_path = QtWidgets.QPushButton(self.Image1)
        self.Video_path.setGeometry(QtCore.QRect(10, 10, 90, 28))
        self.Video_path.setObjectName("Video_path")
        self.video_path_text = QtWidgets.QLabel(self.Image1)
        self.video_path_text.setGeometry(QtCore.QRect(110, 20, 431, 16))
        self.video_path_text.setObjectName("video_path_text")
        self.video_holder = QtWidgets.QLabel(self.Image1)
        self.video_holder.setGeometry(QtCore.QRect(10, 60, 761, 450))
        self.video_holder.setStyleSheet("Background-color: #000;")
        self.video_holder.setText("")
        self.video_holder.setObjectName("video_holder")
        self.play_buttom = QtWidgets.QPushButton(self.Image1)
        self.play_buttom.setGeometry(QtCore.QRect(10, 530, 90, 28))
        self.play_buttom.setObjectName("play_buttom")
        self.checkBox = QtWidgets.QCheckBox(self.Image1)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(690, 20, 75, 18))
        self.checkBox.setObjectName("checkBox")
        self.tabWidget.addTab(self.Image1, "")
        self.recognition_rate = QtWidgets.QLabel(self.centralwidget)
        self.recognition_rate.setGeometry(QtCore.QRect(720, 620, 61, 21))
        self.recognition_rate.setObjectName("recognition_rate")
        self.Image_result = QtWidgets.QLabel(self.centralwidget)
        self.Image_result.setGeometry(QtCore.QRect(630, 620, 81, 21))
        self.Image_result.setObjectName("Image_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuModel = QtWidgets.QMenu(self.menuFile)
        self.menuModel.setObjectName("menuModel")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.menuCamera = QtWidgets.QMenu(self.menuTool)
        self.menuCamera.setObjectName("menuCamera")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLabel = QtWidgets.QAction(MainWindow)
        self.actionLabel.setCheckable(True)
        self.actionLabel.setChecked(True)
        self.actionLabel.setObjectName("actionLabel")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionAbout_Us = QtWidgets.QAction(MainWindow)
        self.actionAbout_Us.setWhatsThis("")
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.actionLPRNet = QtWidgets.QAction(MainWindow)
        self.actionLPRNet.setObjectName("actionLPRNet")
        self.actionObject_Detection = QtWidgets.QAction(MainWindow)
        self.actionObject_Detection.setObjectName("actionObject_Detection")
        self.actionLicense_Plate_Recognition = QtWidgets.QAction(MainWindow)
        self.actionLicense_Plate_Recognition.setObjectName("actionLicense_Plate_Recognition")
        self.actionCameras = QtWidgets.QAction(MainWindow)
        self.actionCameras.setCheckable(False)
        self.actionCameras.setEnabled(True)
        self.actionCameras.setObjectName("actionCameras")
        self.menuModel.addAction(self.actionLPRNet)
        self.menuModel.addAction(self.actionObject_Detection)
        self.menuModel.addAction(self.actionLicense_Plate_Recognition)
        self.menuFile.addAction(self.menuModel.menuAction())
        self.menuFile.addAction(self.actionLabel)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveAs)
        self.menuCamera.addSeparator()
        self.menuCamera.addAction(self.actionCameras)
        self.menuTool.addAction(self.menuCamera.menuAction())
        self.menuHelp.addAction(self.actionAbout_Us)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LPRNet GUI"))
        MainWindow.setProperty("text", _translate("MainWindow", "Default"))
        self.Image_path.setText(_translate("MainWindow", "Choose image"))
        self.Image_path_text.setText(_translate("MainWindow", "Path"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Image), _translate("MainWindow", "Image"))
        self.Video_path.setText(_translate("MainWindow", "Choose video"))
        self.video_path_text.setText(_translate("MainWindow", "Path"))
        self.play_buttom.setText(_translate("MainWindow", "Play"))
        self.checkBox.setText(_translate("MainWindow", "Real time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Image1), _translate("MainWindow", "Video"))
        self.recognition_rate.setText(_translate("MainWindow", "0"))
        self.Image_result.setText(_translate("MainWindow", "Processing time :"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuModel.setTitle(_translate("MainWindow", "Models"))
        self.menuTool.setTitle(_translate("MainWindow", "Setting"))
        self.menuCamera.setTitle(_translate("MainWindow", "Camera"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLabel.setText(_translate("MainWindow", "Label"))
        self.actionLabel.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As..."))
        self.actionAbout_Us.setText(_translate("MainWindow", "About Us"))
        self.actionLPRNet.setText(_translate("MainWindow", "LPRNet"))
        self.actionObject_Detection.setText(_translate("MainWindow", "Vehicle Detection"))
        self.actionLicense_Plate_Recognition.setText(_translate("MainWindow", "License Plate Recognition"))
        self.actionCameras.setText(_translate("MainWindow", "No camera available"))

